### ISSUE TITLE
Implementar ORM

### ISSUE THREAD

**Issue by matiasah** [matiasah/trackthor#8]

**Comment by MRROOX** [comment]
Se crea una primera versión del ORM, es necesario tomar una decisión referente a la clase Usuario, de la cual heredan otros tipos de usuario, en Spring JPA no se cual es la mejor forma de manejarlo, por ello debemos revisarlo, para también aprender :+1: .

**Por el momento he dejado a cada uno de los usuario como una clase por separado (SIN LA HERENCIA).**


![Selección_005](https://user-images.githubusercontent.com/17860355/57103965-28defb00-6cf5-11e9-86f6-73e4d5a90ea4.png)

**Comment by matiasah** [comment]
Puedes abrir un pull request a la rama principal?
